# Comment

Expr:     Product add_sub Product
          Product

Product:  Value mul_div Value &"positive-lookahead" !negative-lookahead
          Value

add_sub:  '+'
          '-'

mul_div:  '*'
          '/'

Value:    '(' Expr ')'
          Number

Number:   Digit+

Digit:    '0'
          '1'
          '2'
          '3'
          '4'
          '5'
          '6'
          '7'
          '8'
          '9'

