# ./rat -d timewarrior.peg 'start yesterday foo bar :hint'

# Grammar for the Timewarrior command line.
# When complete, timew.git/src/CLI.* can be replaced.

CLI: Command Range? Tag* Hint*

Command: <sep>* "start"
         <sep>* "stop"
         <sep>* "track"

Range:   <sep>* Datetime <sep>* '-'  <sep>* Datetime
         <sep>* Datetime <sep>* "to" <sep>* Datetime

Tag:     <sep>* <word>

Hint:    <sep>* ":yes"

import datetime.peg
